name: gmdsitut
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas>=2.0
  - numpy<2 
  - matplotlib 
  - openpyxl
  - xlrd
  - jupyter 
  - notebook 
  - scipy 
  - shapely
  - rtree
  - pyproj>=2.0
  - pyshp
  - psutil
  - git
  - nbconvert
  - pip
  - pip:
       - flopy == 3.9.3
       - git+https://github.com/pypest/pyemu.git@develop
       - pypestutils == 0.3.0


